logging:
  level: info
paseto:
  expiration: 8766h # 1 year
  keyPath: "./settings/paseto.key"
  publicPath: "./settings/paseto.pub"
  secretKey: "your-secret-key"
  version: v4
runners:
  - host: 127.0.0.1:11434
    name: ollama
    path: /
    scheme: http
server:
  address: ":8443"
  certificatePath: ""
  keyPath: ""
  readTimeoutSeconds: 5s
  writeTimeoutSeconds: 5s